from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)

from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors
from reportlab.lib.units import inch


def create_pdf(report_text):

    filename = "Resume_Analysis_Report.pdf"

    doc = SimpleDocTemplate(
        filename,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )

    styles = getSampleStyleSheet()

    story = []

    # -----------------------------
    # Title
    # -----------------------------

    title = Paragraph(
        "<font size=22><b>AI Career Assistant Pro</b></font>",
        styles["Title"]
    )

    story.append(title)

    story.append(Spacer(1, 10))

    subtitle = Paragraph(
        "<font size=14>Professional Resume Analysis Report</font>",
        styles["Heading2"]
    )

    story.append(subtitle)

    story.append(Spacer(1, 20))

    # -----------------------------
    # Header Table
    # -----------------------------

    table_data = [
        ["Report Type", "AI Resume Analysis"],
        ["Generated By", "AI Career Assistant Pro"],
        ["Status", "Completed"]
    ]

    table = Table(table_data, colWidths=[2.3 * inch, 3.2 * inch])

    table.setStyle(TableStyle([

        ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

        ("TEXTCOLOR", (0, 0), (-1, -1), colors.black),

        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),

        ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),

        ("FONTNAME", (0, 0), (-1, -1), "Helvetica-Bold"),

        ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

    ]))

    story.append(table)

    story.append(Spacer(1, 25))

    # -----------------------------
    # Report Content
    # -----------------------------

    for line in report_text.split("\n"):

        line = line.strip()

        if not line:
            continue

        if line.startswith("#"):

            story.append(
                Paragraph(
                    f"<font size=16 color='darkblue'><b>{line.replace('#','')}</b></font>",
                    styles["Heading2"]
                )
            )

        elif line.startswith("-"):

            story.append(
                Paragraph(
                    f"• {line[1:].strip()}",
                    styles["BodyText"]
                )
            )

        else:

            story.append(
                Paragraph(
                    line,
                    styles["BodyText"]
                )
            )

        story.append(Spacer(1, 6))

    # -----------------------------
    # Footer
    # -----------------------------

    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "<font color='grey'><i>Generated using AI Career Assistant Pro | Python | Streamlit | Google Gemini</i></font>",
            styles["Italic"]
        )
    )

    doc.build(story)

    return filename